spring:
  main:
    web-application-type: none
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    hikari:
      connection-timeout: 1000
      minimum-idle: 2
      maximum-pool-size: 8
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          fetch_size: 16
          batch_size: 16
        order_inserts: true
        order_udpates: true
        max_fetch_depth: 0
        default_batch_fetch_size: 16
  kafka:
    topic: testTopic
    partitions: 5
    consumer:
      bootstrap-servers: localhost:9092
      group-id: batch
      fetch-max-wait: 1000
      max-poll-records: 10